baseURL: "https://etrama.github.io/"
title: Old Habits AI Hard
paginate: 10
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true

params:
  enableEmoji: true
  homeInfoParams:
    Title: "AI come in peace \U0001F609 \U0001F44B"
    Content: "I'm Kaushik Moudgalya, welcome to my slice of the internet, Old Habits AI Hard.  
    I am a soon to be Master's graduate from the University of Montreal & MILA. I specialize in Machine Learning and Deep Learning.  
    Check out my projects or blog or just rest here before further internet travels. As you might have noticed, I like puns.
    


    This page is mostly a collection of my blogs and projects. For more specific information about me, please use the links below.
    Site currently under construction, updates in progress!
    "
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Kaushik Moudgalya's personal website"
    keywords: [Kaushik, Banana Leopard, Blog, Portfolio, PaperMod]
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
  socialIcons:
    - name: github
      title: "Github"
      url: "https://github.com/Etrama"
    - name: linkedin
      title: "LinkedIn"
      url : "https://www.linkedin.com/in/kaushik-moudgalya/"
    - name: medium
      url: "https://kaushikmoudgalya.medium.com/"
    - name: cv
      title: CV
      url: "https://drive.google.com/file/d/1Pao1fxwIveSwyJ0Q7XTYfweq6JITQ3t5/view?usp=share_link"
    - name: googlescholar
      title: Google Scholar
      url: "https://scholar.google.com/citations?user=yYWadqsAAAAJ&hl=en"
    - name: twitter
      url: "https://twitter.com/Banana_Leopard"
    - name: email
      url: "mailto:kaushikmoudgalya@gmail.com"

  # editPost:
  #       URL: "https://github.com/<gitlab user>/<repo name>/tree/<branch name>/<path to content>/"
  #       Text: "Suggest Changes" # edit text
  #       appendFilePath: true # to append file path to Edit link    
  assets:
        disableFingerprinting: true
  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  # ShowWordCount: true
  ShowAuthorInList: true
  ShowCodeCopyButtons: true
  UseHugoToc: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

# for search
outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary
        
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: Home
      name: Home
      url: /
      weight: 50
    # - identifier: faq
    #   name: Q&A
    #   url: /faq/
    #   weight: 50
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 60
enableRobotsTXT: true
##################################################################################################################
### Other settings we could use but don't need right now, can be found below:
# buildDrafts: false
# buildFuture: false
# buildExpired: false

# googleAnalytics: UA-123-45

# minify:
#   disableXML: true
#   minifyOutput: true

# params:
#   env: production # to enable google analytics, opengraph, twitter-cards and schema.
#   title: ExampleSite
#   description: "ExampleSite description"
#   keywords: [Blog, Portfolio, PaperMod]
#   author: Me
#   # author: ["Me", "You"] # multiple authors
#   images: ["<link or path of image for opengraph, twitter-cards>"]
#   DateFormat: "January 2, 2006"
#   defaultTheme: auto # dark, light
#   disableThemeToggle: false

#   ShowReadingTime: true
#   ShowShareButtons: true
#   ShowPostNavLinks: true
#   ShowBreadCrumbs: true
#   ShowCodeCopyButtons: false
#   ShowWordCount: true
#   ShowRssButtonInSectionTermList: true
#   UseHugoToc: true
#   disableSpecial1stPost: false
#   disableScrollToTop: false
#   comments: false
#   hidemeta: false
#   hideSummary: false
#   showtoc: false
#   tocopen: false

#   assets:
#     # disableHLJS: true # to disable highlight.js
#     # disableFingerprinting: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

#   label:
#     text: "Home"
#     icon: /apple-touch-icon.png
#     iconHeight: 35

#   # profile-mode
#   profileMode:
#     enabled: false # needs to be explicitly set
#     title: ExampleSite
#     subtitle: "This is subtitle"
#     imageUrl: "<img location>"
#     imageWidth: 120
#     imageHeight: 120
#     imageTitle: my image
#     buttons:
#       - name: Posts
#         url: posts
#       - name: Tags
#         url: tags

#   # home-info mode
#   homeInfoParams:
#     Title: "Hi there \U0001F44B"
#     Content: Welcome to my blog


analytics:
  google:
    SiteVerificationTag: "G-ZQRQFZ413J"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link


# menu:
#   main:
#     - identifier: categories
#       name: categories
#       url: /categories/
#       weight: 10
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 20
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30
# # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai